### ISSUE TITLE
Map/Navigate

### ISSUE THREAD

**Issue by rachnov55** [eouia/MMM-Assistant#61]
Is there anyway for me to have google assistant open up google maps to show me a map/directions?

Asking it for directions now causes the assistant to freeze up on me :/

**Comment by E3V3A** [comment]
Not sure what would be involved to do this. The problem here is opening up the new map window, this is quite a bit of additional programming and added *iframe* module. We have a lot of other thing we need to fix first, so this probably will not be started for quite a while. Good idea though. 

In the mean time, if you can't wait, you can try to see how to implement this in for example MMM-Voice or some of the other voice modules.

**Comment by rachnov55** [comment]
sure I'm still figuring things out myself :D downloaded a few other voice modules that has AI and trying to see what's going on in it.

off topic -->  As I'm a complete noob when it comes to programming (all I do is look at other ppl's scripts/code and figure out what does what, but have no idea how to do it on my own), what languages do you reccommend me to start with learning?

**Comment by E3V3A** [comment]
@rachnov55  
> what languages do you reccommend me to start with learning?

[JavaScript](https://www.w3schools.com/js/default.asp), then Node.js (is also a form of JS) then Python.
