### ISSUE TITLE
FILE MISSING: node-v64-linux-arm-glibc.tar.gz 

### ISSUE THREAD

**Issue by sandradeng** [eouia/MMM-Assistant#70]
When process npm install, ERROR occurred below, any ideas what happened? 

node-pre-gyp ERR! Tried to download(403): https://storage.googleapis.com/grpc-precompiled-binaries/node/grpc/v1.8.0/node-v64-linux-arm-glibc.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for grpc@1.8.0 and node@10.4.1 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)

**Comment by vivek87799** [comment]
@sandradeng I have the same issue were u able to fix it ?
It will be kind if you could help me with this.

**Comment by sandradeng** [comment]
no, i tried some other lib sources but still failed.

**Comment by eouia** [comment]
@sandradeng 
First, thanks for your interesting.
Sorry for announcing this. This module will not be supported anymore. Because the legacy dependencies are too old and complex (including your case). Instead, I suggest you [MMM-AssistantMk2](https://github.com/eouia/MMM-AssistantMk2)
Anyway, have you tried "npm rebuild"? I think there is no precompiled binrary for your system environment. It means you should rebuild it by yourself.
