### ISSUE TITLE
Still work with MM-2.4 update?

### ISSUE THREAD

**Issue by Jacob-Meischner** [eouia/MMM-Assistant#73]
I was just wondering if anyone had any luck getting this module to work after updating their MM to version 2.4?

**Comment by eouia** [comment]
Sorry for my absence, I was stuck in my real world. sorry again.
Frankly says, I'm not supporting this module anymore. I was so disappointed with this module's complexity and difficulty to maintain. A half was due to my poor skill, and the other half was due to incomplete Google Assistant SDK and MagicMirror-Electron problems and... even snowboy stuffs.

Anyway, I can answer your question.

1) If you run your MM as Kiosk mode (`npm start`), you should rebuild your binaries of this module dependencies. Rebuilding could not be impossible, but not easy for non-expert.
2) If you run your MM as serveronly mode (`npm serveronly`), It will work.(maybe)

I think this module owe to old legacy-dependencies, so it's better to abandon this and to make a whole new module. I'm working it now and it is almost done, but cannot promise. Anyway, Sorry again and Thanks for your using.

**Comment by Jacob-Meischner** [comment]
I appreciate the response on both my posts, and yeah that's exactly what I had to do.
